// <auto-generated />
using System;
using EmuWarface.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmuWarface.Database.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("EmuWarface.Database.Model.Profile", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20) unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("BanExpire")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ban_expire");

                    b.Property<uint>("BannerBadge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("banner_badge")
                        .HasDefaultValueSql("'4294967295'");

                    b.Property<uint>("BannerMark")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("banner_mark")
                        .HasDefaultValueSql("'4294967295'");

                    b.Property<uint>("BannerStripe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("banner_stripe")
                        .HasDefaultValueSql("'4294967295'");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("current_timestamp(6)");

                    b.Property<uint?>("CurrentClass")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("current_class");

                    b.Property<ulong>("Experience")
                        .HasColumnType("bigint(20) unsigned")
                        .HasColumnName("experience");

                    b.Property<float>("Fatness")
                        .HasColumnType("float")
                        .HasColumnName("fatness");

                    b.Property<string>("Head")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("head");

                    b.Property<float>("Height")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasColumnName("height")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime>("LastSeen")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_seen")
                        .HasDefaultValueSql("current_timestamp(6)");

                    b.Property<byte>("MissionPassed")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("mission_passed");

                    b.Property<DateTime>("MuteExpire")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("mute_expire");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("nickname");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint(20) unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "ix_profiles_user_id")
                        .HasDatabaseName("ix_profiles_user_id");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("EmuWarface.Database.Model.ProfileAchievement", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("achievement_id");

                    b.Property<DateTime>("CompletionTime")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completion_time");

                    b.Property<ulong>("ProfileId")
                        .HasColumnType("bigint(20) unsigned")
                        .HasColumnName("profile_id");

                    b.Property<int>("Progress")
                        .HasColumnType("int(11)")
                        .HasColumnName("progress");

                    b.HasKey("AchievementId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProfileId" }, "ix_profile_achievements_profile_id")
                        .HasDatabaseName("ix_profile_achievements_profile_id");

                    b.ToTable("profile_achievements", (string)null);
                });

            modelBuilder.Entity("EmuWarface.Database.Model.ProfileItem", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20) unsigned")
                        .HasColumnName("id");

                    b.Property<ulong>("AttachedTo")
                        .HasColumnType("bigint(20) unsigned")
                        .HasColumnName("attached_to");

                    b.Property<DateTime>("BuyTime")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("buy_time");

                    b.Property<ulong>("CatalogId")
                        .HasColumnType("bigint(20) unsigned")
                        .HasColumnName("catalog_id");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("config");

                    b.Property<uint>("DurabilityPoints")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("durability_points");

                    b.Property<DateTime>("ExpirationTime")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiration_time");

                    b.Property<ulong>("Item")
                        .HasColumnType("bigint(20) unsigned")
                        .HasColumnName("item");

                    b.Property<ulong>("ProfileId")
                        .HasColumnType("bigint(20) unsigned")
                        .HasColumnName("profile_id");

                    b.Property<ulong?>("SlotIds")
                        .HasColumnType("bigint(20) unsigned")
                        .HasColumnName("slot_ids");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<uint>("TotalDurabilityPoints")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("total_durability_points");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProfileId" }, "ix_profile_items_profile_id")
                        .HasDatabaseName("ix_profile_items_profile_id");

                    b.ToTable("profile_items", (string)null);
                });

            modelBuilder.Entity("EmuWarface.Database.Model.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20) unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("current_timestamp(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("password")
                        .IsFixedLength();

                    b.Property<ulong>("ProfileId")
                        .HasColumnType("bigint(20) unsigned")
                        .HasColumnName("profile_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProfileId" }, "ix_users_profile_id")
                        .HasDatabaseName("ix_users_profile_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EmuWarface.Database.Model.Profile", b =>
                {
                    b.HasOne("EmuWarface.Database.Model.User", "User")
                        .WithMany("Profiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EmuWarface.Database.Model.ProfileAchievement", b =>
                {
                    b.HasOne("EmuWarface.Database.Model.Profile", "Profile")
                        .WithMany("ProfileAchievements")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_achievements_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("EmuWarface.Database.Model.ProfileItem", b =>
                {
                    b.HasOne("EmuWarface.Database.Model.Profile", "Profile")
                        .WithMany("ProfileItems")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_items_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("EmuWarface.Database.Model.User", b =>
                {
                    b.HasOne("EmuWarface.Database.Model.Profile", "Profile")
                        .WithMany("Users")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("EmuWarface.Database.Model.Profile", b =>
                {
                    b.Navigation("ProfileAchievements");

                    b.Navigation("ProfileItems");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmuWarface.Database.Model.User", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
